language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer self-update
  
install:
  - composer install --no-interaction --prefer-source
  
script:
    ./vendor/bin/phpunit
    ./vendor/phing/phing/bin/phing -f build.xml